language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: ALc4zJXzYqBDa5r9q77M8BojR1dZ6ReDprLguUVgTtf6oNbzoqLbnGYsuuPnTAYUZnQH9pPZpFaXyHmUioZG1y0hKAjEqplOzpwp+poQEJZodQivhWIVPWVZH1DRZfSW5A0m5R3wBwRn/JnWvrfnHnZjO51WdTrcKdypE31fFi2zhI6XOH48ISlaCydtgFFmrFWC/oJtmLVDQiS56ix2SaAo78NR3ZlvzG6N5DTS/pyIY4bOgVwkAe5MzqL+JWIJreji4z1sc2IZ5WSGkSVJHN0PwXUqgL/K+gROEHF7PwlFzAjynMqtYtvkb5L6VnrjJNvD4HyY/Clysctqdibu3NquaS/AKuQY5+TUUUl+t4F+BPyHjNLeuZqxLVtbpScOL5ooBmYYzQ1kSHgJUaFc1LKhQn13J5cOKyzbDQm/g1iYgWPWzqcOznvZuY8vdscG9vD51XNfCZi04Zfc30xQYJptZPRNRpMnpuq3O3bUEJlgSOQyw1cvhcKXnVFPYhUW8b9BQ2Ai2k/PoJ6CwczgxMcxgVH3bTWvc+4GGxhbQKIyzjYjPV70T4tniGjoiqR5pGMLTchDULtdax87DfsTYhhgOU75ZgbEQtsHtpqhDh+DbMIXKcok6Zv23j+7zWyb0Q9TNPXHLIZakFH0st+1JvBcdCElXnfKtcJC8jMT61Q=
