name: PlayerLink
main: com.justinwflory.playerlink.PlayerLink
version: 1.4.2
description: PlayerLink is a Bukkit plugin designed to keep your players informed about your server.
author: jflory7
website: http://dev.bukkit.org/bukkit-plugins/playerlink/

commands:
   playerlink:
      description: Includes info and reloads.
      usage: /playerlink <help, reload>
   website:
      description: Shows the link to a website you set.
      usage: /website
      permission: playerlink.website
      permission-message: You don't have <permission>
   vote:
      description: Shows the link to a voting website you set.
      usage: /vote
      permission: playerlink.vote
      permission-message: You don't have <permission>
   forums:
      description: Shows the link to a forum you set.
      usage: /forums
      permission: playerlink.forums
      permission-message: You don't have <permission>
   shop:
      description: Shows the link to a server shop you set.
      usage: /shop
      permission: playerlink.shop
      permission-message: You don't have <permission>
   voice:
      description: Shows the IP to a voice server you set.
      usage: /voice
      permission: playerlink.voice
      permission-message: You don't have <permission>
   map:
      description: Shows the link to a DynMap page you set.
      usage: /map
      permission: playerlink.dynmap
      permission-message: You don't have <permission>
   wiki:
      description: Shows the link to a wiki you set.
      usage: /wiki
      permission: playerlink.wiki
      permission-message: You don't have <permission>
   facebook:
      description: Shows the link to a Facebook page.
      usage: /facebook
      permission: playerlink.facebook
      permission-message: You don't have <permission>
   twitter:
      description: Shows the link to a Twitter page.
      usage: /twitter
      permission: playerlink.twitter
      permission-message: You don't have <permission>
   youtube:
      description: Shows the link to a YouTube page.
      usage: /youtube
      permission: playerlink.youtube
      permission-message: You don't have <permission>
   google+:
      description: Shows the link to a Google+ page you set.
      usage: /google+
      permission: playerlink.googleplus
      permission-message: You don't have <permission>
   instagram:
      description: Shows the link to an Instagram page you set.
      usage: /instagram
      permission: playerlink.instagram
      permission-message: You don't have <permission>
   link:
      description: Shows the link to any URL you set.
      usage: /link
      permission: playerlink.link
      permission-message: You don't have <permission>

permissions:
    playerlink.*:
        description: Gives access to all PlayerLink commands.
        children:
            playerlink.player.*: true
            playerlink.reload: true
    playerlink.player.*:
        description: Gives access to all player commands.
        children:
            playerlink.help: true
            playerlink.website: true
            playerlink.vote: true
            playerlink.forums: true
            playerlink.shop: true
            playerlink.voice: true
            playerlink.dynmap: true
            playerlink.wiki: true
            playerlink.facebook: true
            playerlink.twitter: true
            playerlink.youtube: true
            playerlink.googleplus: true
            playerlink.instagram: true
            playerlink.link: true
            playerlink.reload: false
    playerlink.help:
        description: Show a list of commands for PlayerLink.
        default: true
    playerlink.website:
        description: Shows the link to a website you set.
        default: true
    playerlink.vote:
        description: Shows the link to a voting website you set.
        default: true
    playerlink.forums:
        description: Shows the link to a forum you set.
        default: true
    playerlink.shop:
        description: Shows the link to a server shop you set.
        default: true
    playerlink.voice:
        description: Shows the IP to a voice server you set.
        default: true
    playerlink.dynmap:
        description: Shows the link to a DynMap page you set.
        default: true
    playerlink.wiki:
        description: Shows the link to a wiki you set.
        default: true
    playerlink.facebook:
        description: Shows the link to a Facebook page you set.
        default: true
    playerlink.twitter:
        description: Shows the link to a Twitter page you set.
        default: true
    playerlink.youtube:
        description: Shows the link to a YouTube page you set.
        default: true
    playerlink.googleplus:
        description: Shows the link to a Google+ page you set.
        default: true
    playerlink.instagram:
        description: Shows the link to an Instagram page you set.
        default: true
    playerlink.link:
        description: Shows the link to any URL you set.
        default: true
    playerlink.reload:
        description: Reload the configuration.
        default: op